In [1]:
import pandas as pd

In [2]:
#import complaints excel
complaints_df = pd.read_csv("CCAPO_2016-2018_Agency_0.csv")
complaints_df

,NCIC,AgencyName,County,ComplaintYear,TotalComplaintsReported,NonCriminalReported,MisdemeanorReported,FelonyReported,TotalComplaintsInDetentionReported,NonCriminalInDetentionReported,...,RaceEthnicityPending,NationalityPending,GenderPending,AgePending,ReligionPending,GenderIdentityExpressionPending,SexualOrientationPending,MentalDisabilityPending,PhysicalDisabilityPending,NoComplaintsFiled
0,6301,Alameda County District Attorney,Alameda,2016,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,False
1,6301,Alameda County District Attorney,Alameda,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,True
2,6301,Alameda County District Attorney,Alameda,2018,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,True
3,6203,Alameda County Fire Department,Alameda,2016,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,True
4,6801,Alameda County Probation Dept,Alameda,2017,6,5,0,1,0,0,...,0,0,0,0,0,0,0,0,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2267,5800,Yuba County Sheriff's Department,Yuba,2017,17,16,1,0,5,5,...,0,0,0,0,0,0,0,0,0,False
2268,5800,Yuba County Sheriff's Department,Yuba,2018,7,7,0,0,0,0,...,0,0,0,0,0,0,0,0,0,False
2269,6458,Yuba County Social Services,Yuba,2016,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,True
2270,6458,Yuba County Social Services,Yuba,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,True
2271,6458,Yuba County Social Services,Yuba,2018,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,True

In [3]:
complaints_df.columns

Index(['NCIC', 'AgencyName', 'County', 'ComplaintYear',
       'TotalComplaintsReported', 'NonCriminalReported', 'MisdemeanorReported',
       'FelonyReported', 'TotalComplaintsInDetentionReported',
       'NonCriminalInDetentionReported',
       ...
       'RaceEthnicityPending', 'NationalityPending', 'GenderPending',
       'AgePending', 'ReligionPending', 'GenderIdentityExpressionPending',
       'SexualOrientationPending', 'MentalDisabilityPending',
       'PhysicalDisabilityPending', 'NoComplaintsFiled'],
      dtype='object', length=113)

In [4]:
#edit/modify columns with total complaints only
total_complaints_df = pd.DataFrame(complaints_df[{'NCIC','County',
                                                  'AgencyName',
                                                  'ComplaintYear', 
                                                  'TotalComplaintsReported',
                                                  'TotalComplaintsSustained',
                                                  'TotalComplaintsExonerated',
                                                  'TotalComplaintsNotSustained',
                                                  'TotalComplaintsUnfounded',
                                                  'TotalComplaintsPending'}])

total_complaints_df = total_complaints_df.reindex(columns = ['NCIC','County',
                                        'AgencyName',
                                        'ComplaintYear', 
                                        'TotalComplaintsReported',
                                        'TotalComplaintsSustained',
                                        'TotalComplaintsExonerated',
                                        'TotalComplaintsNotSustained',
                                        'TotalComplaintsUnfounded',
                                        'TotalComplaintsPending'])

total_complaints_df = total_complaints_df.rename(columns = {
                                        'AgencyName':'Agency',
                                        'ComplaintYear': 'Complaint Year', 
                                        'TotalComplaintsReported': 'Complaints Reported',
                                        'TotalComplaintsSustained':'Complaints Sustained',
                                        'TotalComplaintsExonerated': 'Complaints Exonerated',
                                        'TotalComplaintsNotSustained':'Complaints Not Sustained',
                                        'TotalComplaintsUnfounded': 'Complaints Unfounded',
                                        'TotalComplaintsPending': 'Complaints Pending'})

total_complaints_df

,NCIC,County,Agency,Complaint Year,Complaints Reported,Complaints Sustained,Complaints Exonerated,Complaints Not Sustained,Complaints Unfounded,Complaints Pending
0,6301,Alameda,Alameda County District Attorney,2016,1,0,0,0,1,0
1,6301,Alameda,Alameda County District Attorney,2017,0,0,0,0,0,0
2,6301,Alameda,Alameda County District Attorney,2018,0,0,0,0,0,0
3,6203,Alameda,Alameda County Fire Department,2016,0,0,0,0,0,0
4,6801,Alameda,Alameda County Probation Dept,2017,6,0,0,2,3,1
...,...,...,...,...,...,...,...,...,...,...
2267,5800,Yuba,Yuba County Sheriff's Department,2017,17,1,0,8,1,7
2268,5800,Yuba,Yuba County Sheriff's Department,2018,7,1,0,3,0,3
2269,6458,Yuba,Yuba County Social Services,2016,0,0,0,0,0,0
2270,6458,Yuba,Yuba County Social Services,2017,0,0,0,0,0,0
2271,6458,Yuba,Yuba County Social Services,2018,0,0,0,0,0,0

In [5]:
#find sum of complaints for all rows as total complaints
total =0
for index, row in total_complaints_df.iterrows():
    total = row[4] + row[5] + row[6] + row[7] + row[8] + row[9]
    total_complaints_df.loc[index,'Total Complaints']= total

total_complaints_df.head()

,NCIC,County,Agency,Complaint Year,Complaints Reported,Complaints Sustained,Complaints Exonerated,Complaints Not Sustained,Complaints Unfounded,Complaints Pending,Total Complaints
0,6301,Alameda,Alameda County District Attorney,2016,1,0,0,0,1,0,2.0
1,6301,Alameda,Alameda County District Attorney,2017,0,0,0,0,0,0,0.0
2,6301,Alameda,Alameda County District Attorney,2018,0,0,0,0,0,0,0.0
3,6203,Alameda,Alameda County Fire Department,2016,0,0,0,0,0,0,0.0
4,6801,Alameda,Alameda County Probation Dept,2017,6,0,0,2,3,1,12.0

In [6]:
complaints_per_county_df = total_complaints_df.groupby(['County', 'Complaint Year']).sum()
complaints_per_county_df

                        Complaints Reported  Complaints Sustained  \
County  Complaint Year
Alameda 2016                           1366                   156
        2017                           1452                   106
        2018                           1539                   232
Alpine  2016                              0                     0
        2017                              0                     0
...                                     ...                   ...
Yolo    2017                             44                     2
        2018                             60                     5
Yuba    2016                             25                     4
        2017                             22                     1
        2018                             20                     1

                        Complaints Exonerated  Complaints Not Sustained  \
County  Complaint Year
Alameda 2016                              237                        87
        2017                               68                        34
        2018                              517                       122
Alpine  2016                                0                         0
        2017                                0                         0
...                                       ...                       ...
Yolo    2017                                3                         3
        2018                                4                         8
Yuba    2016                                0                        11
        2017                                0                         9
        2018                                5                         5

                        Complaints Unfounded  Complaints Pending  \
County  Complaint Year
Alameda 2016                             575                 834
        2017                             205                 335
        2018                             936                 863
Alpine  2016                               0                   0
        2017                               0                   0
...                                      ...                 ...
Yolo    2017                              30                   4
        2018                              42                   1
Yuba    2016                               6                   4
        2017                               4                   8
        2018                               6                   3

                        Total Complaints
County  Complaint Year
Alameda 2016                      3255.0
        2017                      2200.0
        2018                      4209.0
Alpine  2016                         0.0
        2017                         0.0
...                                  ...
Yolo    2017                        86.0
        2018                       120.0
Yuba    2016                        50.0
        2017                        44.0
        2018                        40.0

[174 rows x 7 columns]

In [7]:
#find percentages
complaints_per_county_df['Percentage Sustained'] = 100 * complaints_per_county_df['Complaints Sustained']/complaints_per_county_df['Complaints Reported']
complaints_per_county_df['Percentage Exonerated'] = 100 * complaints_per_county_df['Complaints Exonerated']/complaints_per_county_df['Complaints Reported']
complaints_per_county_df['Percentage Not Sustained'] = 100 * complaints_per_county_df['Complaints Not Sustained']/complaints_per_county_df['Complaints Reported']
complaints_per_county_df['Percentage Unfounded'] = 100 * complaints_per_county_df['Complaints Unfounded']/complaints_per_county_df['Complaints Reported']
complaints_per_county_df['Percentage Pending'] = 100 * complaints_per_county_df['Complaints Pending']/complaints_per_county_df['Complaints Reported']
  
    
#drop rows with null values
complaints_per_county_df.dropna(inplace = True)
complaints_per_county_df

                        Complaints Reported  Complaints Sustained  \
County  Complaint Year
Alameda 2016                           1366                   156
        2017                           1452                   106
        2018                           1539                   232
Amador  2016                              6                     2
        2017                              9                     4
...                                     ...                   ...
Yolo    2017                             44                     2
        2018                             60                     5
Yuba    2016                             25                     4
        2017                             22                     1
        2018                             20                     1

                        Complaints Exonerated  Complaints Not Sustained  \
County  Complaint Year
Alameda 2016                              237                        87
        2017                               68                        34
        2018                              517                       122
Amador  2016                                1                         0
        2017                                1                         0
...                                       ...                       ...
Yolo    2017                                3                         3
        2018                                4                         8
Yuba    2016                                0                        11
        2017                                0                         9
        2018                                5                         5

                        Complaints Unfounded  Complaints Pending  \
County  Complaint Year
Alameda 2016                             575                 834
        2017                             205                 335
        2018                             936                 863
Amador  2016                               2                   1
        2017                               3                   1
...                                      ...                 ...
Yolo    2017                              30                   4
        2018                              42                   1
Yuba    2016                               6                   4
        2017                               4                   8
        2018                               6                   3

                        Total Complaints  Percentage Sustained  \
County  Complaint Year
Alameda 2016                      3255.0             11.420205
        2017                      2200.0              7.300275
        2018                      4209.0             15.074724
Amador  2016                        12.0             33.333333
        2017                        18.0             44.444444
...                                  ...                   ...
Yolo    2017                        86.0              4.545455
        2018                       120.0              8.333333
Yuba    2016                        50.0             16.000000
        2017                        44.0              4.545455
        2018                        40.0              5.000000

                        Percentage Exonerated  Percentage Not Sustained  \
County  Complaint Year
Alameda 2016                        17.349927                  6.368960
        2017                         4.683196                  2.341598
        2018                        33.593242                  7.927225
Amador  2016                        16.666667                  0.000000
        2017                        11.111111                  0.000000
...                                       ...                       ...
Yolo    2017                         6.818182                  6.818182
        2018                         6.666667                 13.333333
Yuba    2016                         0.000000                 44.000000
        2017                         0.000000                 40.909091
        2018                        25.000000                 25.000000

                        Percentage Unfounded  Percentage Pending
County  Complaint Year
Alameda 2016                       42.093704           61.054173
        2017                       14.118457           23.071625
        2018                       60.818713           56.075374
Amador  2016                       33.333333           16.666667
        2017                       33.333333           11.111111
...                                      ...                 ...
Yolo    2017                       68.181818            9.090909
        2018                       70.000000            1.666667
Yuba    2016                       24.000000           16.000000
        2017                       18.181818           36.363636
        2018                       30.000000           15.000000

[169 rows x 12 columns]

In [73]:
# to csv
complaints_per_county_df.to_csv('police_complaints_per_county.csv')

In [61]:
#import budget excel
budget_df = pd.read_csv("County_-_Expenditures.csv")
budget_df

,Entity Name,Fiscal Year,Type,Form/Table,Category,Subcategory 1,Subcategory 2,Line Description,Values,Zip Code,Estimated Population,Area in Sq. Miles,Row Number
0,Alameda,2017,Expenditures,PERS_SERV,Internal Service Fund,Operating Expenses,Personnel Services_Internal Service Fund,Personnel Services_Internal Service Fund,85254800,94612,1645359,825,201710571644
1,Alameda,2017,Expenditures,CONTRACT_SERV,Internal Service Fund,Operating Expenses,Contractual Services_Internal Service Fund,Contractual Services_Internal Service Fund,14435608,94612,1645359,825,201710571643
2,Alameda,2017,Expenditures,MATERIAL_SUPP,Internal Service Fund,Operating Expenses,Materials and Supplies_Internal Service Fund,Materials and Supplies_Internal Service Fund,0,94612,1645359,825,201710571642
3,Alameda,2017,Expenditures,GEN_ADMIN_EXP,Internal Service Fund,Operating Expenses,General and Administrative Expenses_Internal S...,General and Administrative Expenses_Internal S...,132880698,94612,1645359,825,201710571641
4,Alameda,2017,Expenditures,DEPR_AMORT_EXP,Internal Service Fund,Operating Expenses,Depreciation and Amortization Expenses_Interna...,Depreciation and Amortization Expenses_Interna...,5348259,94612,1645359,825,201710571640
...,...,...,...,...,...,...,...,...,...,...,...,...,...
231643,Yuba,2018,Expenditures,GEN_RECREATION_CULT,Debt Service and Capital Outlay,Capital Outlay,General,Recreation and Cultural Services_General,6904,95901-5273,74727,639,201810011005
231644,Yuba,2018,Expenditures,SR_RECREATION_CULT,Debt Service and Capital Outlay,Capital Outlay,Special Revenue,Recreation and Cultural Services_Special Revenue,0,95901-5273,74727,639,201810011004
231645,Yuba,2018,Expenditures,DEBT_RECREATION_CULT,Debt Service and Capital Outlay,Capital Outlay,Debt Service,Recreation and Cultural Services_Debt Service,0,95901-5273,74727,639,201810011003
231646,Yuba,2018,Expenditures,CAPPROJ_RECREATION_CULT,Debt Service and Capital Outlay,Capital Outlay,Capital Projects,Recreation and Cultural Services_Capital Projects,0,95901-5273,74727,639,201810011002
231647,Yuba,2018,Expenditures,PERM_RECREATION_CULT,Debt Service and Capital Outlay,Capital Outlay,Permanent,Recreation and Cultural Services_Permanent,0,95901-5273,74727,639,201810011001

In [62]:
#return only public protection budgets
pprotection_df = budget_df.loc[budget_df.Category == 'Public Protection']

In [63]:
#subcategory 1 values
pprotection_df = pprotection_df.rename(columns = {'Subcategory 1':'Subcategory'})

In [64]:
pprotection_df = pprotection_df.replace({'Subcategory': ['Police Protection', 
                                                       'Police Protection_Operating Expenditures', 
                                                       'Police Protection_Capital Outlay', 
                                                       'Other Protection', 'Detention and Correction', 'Judicial',
                                                       'Protective Inspection', 'Protection - Other', 'Protection â€“ Other']}, 'Policing/Law Enforcement')
pprotection_df['Subcategory'].unique()

array(['Policing/Law Enforcement', 'Fire Protection',
       'Flood Control - Soil and Water Conservation',
       'Fire Protection_Operating Expenditures',
       'Fire Protection_Capital Outlay',
       'Flood Control - Soil And Water Conservation_Operating Expenditures',
       'Flood Control - Soil And Water Conservation_Capital Outlay'],
      dtype=object)

In [65]:
pprotection_df.head()

,Entity Name,Fiscal Year,Type,Form/Table,Category,Subcategory,Subcategory 2,Line Description,Values,Zip Code,Estimated Population,Area in Sq. Miles,Row Number
284,Alameda,2017,Expenditures,GEN_TRIAL_COURT_MAINT,Public Protection,Policing/Law Enforcement,General,Trial Court Maintenance of Effort (MOE)(GC 772...,30308403,94612,1645359,825,201710571360
285,Alameda,2017,Expenditures,SR_TRIAL_COURT_MAINT,Public Protection,Policing/Law Enforcement,Special Revenue,Trial Court Maintenance of Effort (MOE)(GC 772...,0,94612,1645359,825,201710571359
286,Alameda,2017,Expenditures,DEBT_TRIAL_COURT_MAINT,Public Protection,Policing/Law Enforcement,Debt Service,Trial Court Maintenance of Effort (MOE)(GC 772...,0,94612,1645359,825,201710571358
287,Alameda,2017,Expenditures,CAPPROJ_TRIAL_COURT_MAINT,Public Protection,Policing/Law Enforcement,Capital Projects,Trial Court Maintenance of Effort (MOE)(GC 772...,0,94612,1645359,825,201710571357
288,Alameda,2017,Expenditures,PERM_TRIAL_COURT_MAINT,Public Protection,Policing/Law Enforcement,Permanent,Trial Court Maintenance of Effort (MOE)(GC 772...,0,94612,1645359,825,201710571356

In [66]:
pprotection_df = pprotection_df.loc[pprotection_df.Subcategory == 'Policing/Law Enforcement']
pprotection_df = pprotection_df.drop(columns=['Type', 'Form/Table', 'Subcategory', 'Line Description', 'Area in Sq. Miles', 'Row Number'])
pprotection_df.head()

,Entity Name,Fiscal Year,Category,Subcategory 2,Values,Zip Code,Estimated Population
284,Alameda,2017,Public Protection,General,30308403,94612,1645359
285,Alameda,2017,Public Protection,Special Revenue,0,94612,1645359
286,Alameda,2017,Public Protection,Debt Service,0,94612,1645359
287,Alameda,2017,Public Protection,Capital Projects,0,94612,1645359
288,Alameda,2017,Public Protection,Permanent,0,94612,1645359

In [67]:
pprotection_df = pprotection_df.rename(columns = {'Subcategory 2':'Subcategory'})
pprotection_df

,Entity Name,Fiscal Year,Category,Subcategory,Values,Zip Code,Estimated Population
284,Alameda,2017,Public Protection,General,30308403,94612,1645359
285,Alameda,2017,Public Protection,Special Revenue,0,94612,1645359
286,Alameda,2017,Public Protection,Debt Service,0,94612,1645359
287,Alameda,2017,Public Protection,Capital Projects,0,94612,1645359
288,Alameda,2017,Public Protection,Permanent,0,94612,1645359
...,...,...,...,...,...,...,...
231423,Yuba,2018,Public Protection,General,0,95901-5273,74727
231424,Yuba,2018,Public Protection,Special Revenue,250,95901-5273,74727
231425,Yuba,2018,Public Protection,Debt Service,0,95901-5273,74727
231426,Yuba,2018,Public Protection,Capital Projects,0,95901-5273,74727
231427,Yuba,2018,Public Protection,Permanent,0,95901-5273,74727

In [69]:
pprotection_df = pprotection_df.replace({'Subcategory': ['Police Protection_Operating Expenditures',
       'Police Protection_Capital Outlay']}, 'Police Protection')
pprotection_df['Subcategory'].unique()

array(['General', 'Special Revenue', 'Debt Service', 'Capital Projects',
       'Permanent',
       'Trial Court Maintenance Of Effort (MOE) (GC 77201.1 - Remitted to the State)_Operating Expenditures',
       'Fifty Percent Excess Revenue Calculation (GC 77205 - Remitted to the State)_Operating Expenditures',
       'Other Trial Court (Incl Non-Rule 810-Facility Related and MOE Penalties GC 68065)_Operating Expenditures',
       'County Clerk_Operating Expenditures',
       'Grand Jury (Including Audit)_Operating Expenditures',
       'District Attorney - Prosecution_Operating Expenditures',
       'District Attorney - Family Support_Operating Expenditures',
       'Public Defender_Operating Expenditures',
       'Court Appointed Counsel_Operating Expenditures',
       'Other_Operating Expenditures_Judicial',
       'Trial Court Maintenance Of Effort (MOE) (GC 77201.1 - Remitted to the State)_Capital Outlay',
       'Fifty Percent Excess Revenue Calculation (GC 77205 - Remitted to the State)_Capital Outlay',
       'Other Trial Court (Include Non-Rule 810-Facility Related and MOE Penalties GC 68065)_Capital Outlay',
       'County Clerk_Capital Outlay',
       'Grand Jury (Including Audit)_Capital Outlay',
       'District Attorney - Prosecution_Capital Outlay',
       'District Attorney - Family Support_Capital Outlay',
       'Public Defender_Capital Outlay',
       'Court Appointed Counsel_Capital Outlay',
       'Other_Capital Outlay_Judicial', 'Police Protection',
       'Adult Detention_Operating Expenditures',
       'Juvenile Detention_Operating Expenditures',
       'Probation_Operating Expenditures',
       'Adult Detention_Capital Outlay',
       'Juvenile Detention_Capital Outlay', 'Probation_Capital Outlay',
       'Agricultural Commissioner_Operating Expenditures',
       'Building Inspector_Operating Expenditures',
       'Livestock Inspector_Operating Expenditures',
       'Sealer of Weights and Measures_Operating Expenditures',
       'Agricultural Commissioner_Capital Outlay',
       'Building Inspector_Capital Outlay',
       'Livestock Inspector_Capital Outlay',
       'Sealer of Weights and Measures_Capital Outlay',
       'LAFCO_Operating Expenditures', 'Recorder_Operating Expenditures',
       'Coroner_Operating Expenditures',
       'Emergency Services_Operating Expenditures',
       'Planning and Zoning_Operating Expenditures',
       'Pound_Operating Expenditures',
       'Other_Operating Expenditures_Other Protection',
       'LAFCO_Capital Outlay', 'Recorder_Capital Outlay',
       'Coroner_Capital Outlay', 'Emergency Services_Capital Outlay',
       'Planning and Zoning_Capital Outlay', 'Pound_Capital Outlay',
       'Other_Capital Outlay_Other Protection'], dtype=object)

In [71]:
pprotection_df = pprotection_df.loc[pprotection_df.Subcategory == 'Police Protection']
pprotection_df.head()

,Entity Name,Fiscal Year,Category,Subcategory,Values,Zip Code,Estimated Population
36815,Alameda,2016,Public Protection,Police Protection,147607043,94612,1627865
36816,Alameda,2016,Public Protection,Police Protection,2331954,94612,1627865
37013,Alpine,2016,Public Protection,Police Protection,2881170,96120,1166
37014,Alpine,2016,Public Protection,Police Protection,46165,96120,1166
37211,Amador,2016,Public Protection,Police Protection,8838229,95642,37707

In [72]:
# to CSV
pprotection_df.to_csv('county_budget_police_protection.csv')